services:
  django_service:
    build:
      context: .
      dockerfile: deploy/django/Dockerfile
    command: python3 manage.py runserver 0:8033
    ports:
      - 8000:8033
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file: .env
    depends_on:
      - postgres_service

  celery_service:
    build:
      context: .
      dockerfile: deploy/django/Dockerfile
    command: /celery
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file: .env
    depends_on:
      - postgres_service
      - redis_service

  celery_beat_service:
    build:
      context: .
      dockerfile: deploy/django/Dockerfile
    command: /celery-beat
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file: .env
    depends_on:
      - postgres_service
      - redis_service

  postgres_service:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=1
    ports:
      - 5432:5432
    volumes:
      - new_pg_data:/var/lib/postgresql/data

  redis_service:
    image: redis:alpine
    #    ports:
    #      - 6380:6379
    env_file: .env
    volumes:
      - redis_data:/data

  flower_service:
    build:
      context: .
      dockerfile: deploy/django/Dockerfile
    command: /flower
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file: .env
    ports:
      - 5001:5001
    depends_on:
      - postgres_service
      - redis_service
      - celery_service

volumes:
  new_pg_data:
  static_volume:
  media_volume:
  redis_data: